const CONST = {
    POP_UP_WINDOW_HEIGHT: "600px", // use it as minHeight
    POP_UP_WINDOW_WIDTH: "600px",
    POP_UP_WINDOW_PRIMARY_BG: "#F24B6A",
    POP_UP_WINDOW_SECONDARY_BG:  "#F27983",
    MAIN_TITLE: "Google Chrome Timer",
    PRIMARY_BTN_CREATE_TIMER: "Create Timer",
    PRIMARY_BTN_RESET_TIMER: "Reset Timer",
    RESET_CONFIRMATION_YES: "Yes",
    RESET_CONFIRMATION_NO: "No",
    RESET_CONFIRMATION_WIDTH: "250px",
    RESET_CONFIRMATION_HEIGHT: "110px",
    RESET_CONFIRMATION_MESSAGE: "Are you sure?",
    CREATE_TIMER_TITLE: "Type name of your Timer",
    CREATE_TIMER_TITLE_WIDTH: "300px",
    CREATE_TIMER_TITLE_HEIGHT: "160px",
    LOCAL_STORAGE_SECTIONS_KEY: "sections",
    TIMER_SECTION_HEIGHT: "80px"
}


export default CONST;